### ISSUE TITLE
[installation] AssertionError: version_keyword expects a dict or True

### ISSUE THREAD

**Issue by jettjaniak** [neelnanda-io/PySvelte#20]
MacOS 14
Python 3.10.13, installed with brew
setuptools 68.2.2
setuptools_scm 8.0.4
```
% pip install git+https://github.com/neelnanda-io/PySvelte
Collecting git+https://github.com/neelnanda-io/PySvelte
  Cloning https://github.com/neelnanda-io/PySvelte to /private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-req-build-pbo6o6hm
  Running command git clone --filter=blob:none --quiet https://github.com/neelnanda-io/PySvelte /private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-req-build-pbo6o6hm
  Resolved https://github.com/neelnanda-io/PySvelte to commit 6f5d971a148d40fb7481d400ae74551b37340e83
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/jett/Documents/jett/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jett/Documents/jett/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/jett/Documents/jett/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 680, in finalize_options
          ep(self)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 700, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/private/var/folders/dx/pd9ycs4j6mdgyss58ywfr_pc0000gn/T/pip-build-env-qvw7q95k/normal/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py", line 80, in version_keyword
          assert isinstance(value, dict), "version_keyword expects a dict or True"
      AssertionError: version_keyword expects a dict or True
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by BiEchi** [comment]
This is also the case for Linux server. Did you find a solution? @jettjaniak

**Comment by BiEchi** [comment]
Just found the solution: replace `setup.py` with `pyproject.toml` with content below:

```
[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "PySvelte"
version = "1.0.0"
description = "A library for visualizing and interpreting model activations within a Jupyter Notebook"
license = "LICENSE"

[tool.poetry.dependencies]
python = "^3.6"
einops = "^0.3"
numpy = "^1.18"
torch = "^1.0"
datasets = "^1.0"
transformers = "^3.0"
tqdm = "^4.0"
pandas = "^1.0"
typeguard = "^2.0"

[tool.poetry.scripts]

[tool.poetry.extras]

[tool.poetry.dev-dependencies]
```

**Comment by TanayB11** [comment]
If you're not using poetry, you can comment out these lines in setup.py.

```
    # use_scm_version=False,
    # setup_requires=['setuptools_scm'],
```

However this results in another error for me:

```
FileNotFoundError: [Errno 2] No such file or directory: 'npm'
<pysvelte.html.Html at 0x155dada80>
```
